controller:
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: linux
  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/os: linux
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
    externalTrafficPolicy: Local
defaultBackend:
  nodeSelector:
    kubernetes.io/os: linux
