influxdb2:
  enabled: false

postgresql:
  enabled: false

databaseExternal:
  enabled: true
  urlFromExistingSecret:
    enabled: true
    name: flagsmith-db
    key: url

service:
  frontend:
    type: LoadBalancer
  api:
    type: LoadBalancer
